name = "OrgNest"
license = "MIT"
licenselink = "https://github.com/himadoya/OrgNest/blob/main/LICENSE.md"
description = "OrgNest is a modern, responsive Hugo theme designed for organizations, teams, and communities. It features a clean layout, content-focused design, and components for blogs, team profiles, portfolios, and more."
min_version = "0.116.0"

homepage = "https://github.com/himadoya/OrgNest"
demosite = "https://orgnest.netlify.app"

tags = ["organization", "blog", "portfolio", "team", "company", "responsive", "clean", "accessible"]
features = ["modular layout", "search integration", "tags & categories", "team profiles", "project portfolio", "historical timeline", "SEO optimized"]

[author]
  name = "HIMADOYA+"
  homepage = "https://himadoya.org"
